# Generated by Django 5.0.3 on 2024-03-15 12:56

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='shop/images', validators=[shop.validators.validate_file_size]),
        ),
    ]
