# Generated by Django 5.0.3 on 2024-03-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
