# Generated by Django 5.0.3 on 2024-03-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.userprofile'),
        ),
    ]
